project:
  type: mcanouil
  output-dir: _site
  post-render:
    - assets/scripts/slides-to-pdf.sh
  resources:
    - assets/images/social-card.png
  render:
    - "**.qmd"
    - "sessions/01-introduction-setup/index.qmd"
    - "sessions/02-authoring-essentials/index.qmd"
    - "sessions/03-embedding-computations-code/index.qmd"
    - "sessions/04-formats-projects/index.qmd"
    - "sessions/05-formatting-branding/index.qmd"
    - "sessions/06-publishing/index.qmd"
    - "sessions/07-closing-next-steps/index.qmd"

date-modified: today
mc-hide-navbar-title: false

copyright: "© 2026 Mickaël CANOUIL"
license: CC BY-NC-SA

date-meta: 2026-02-06
image: assets/images/social-card.png

website:
  title: "Mastering Quarto CLI"
  description: "Learn how to use Quarto CLI for your data science projects."
  site-url: https://m.canouil.dev/mastering-quarto-cli/
  repo-url: https://github.com/mcanouil/mastering-quarto-cli
  repo-actions: []
  image: assets/images/social-card.png
  image-alt: "Quarto Workshop promotional card showing seven-session curriculum from Introduction and Setup through Publishing with dark teal background"
  navbar: false
  page-footer:
    background: dark
    foreground: light
    left: |
      Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org).
    center: |
      &copy; []{#current-year} [Mickaël CANOUIL](https://mickael.canouil.fr). [{{< iconify octicon:heart-fill-16 title="Heart" label="Heart" >}} Sponsor](https://github.com/sponsors/mcanouil?o=esb).
  sidebar:
    logo: dark
    background: dark
    foreground: light
    style: docked
    search: true
    pinned: true
    align: center
    collapse-level: 2
    contents:
      - text: Home
        href: index.qmd
      - text: Program
        href: program/index.qmd
      - text: "---"
      - section: "Part 1"
        contents:
          - href: sessions/01-introduction-setup/index.qmd
          - href: sessions/02-authoring-essentials/index.qmd
          - href: sessions/03-embedding-computations-code/index.qmd
      - text: "---"
      - section: "Part 2"
        contents:
          - href: sessions/04-formats-projects/index.qmd
          - href: sessions/05-formatting-branding/index.qmd
          - href: sessions/06-publishing/index.qmd
          - href: sessions/07-closing-next-steps/index.qmd

brand: _brand.yml
format: mcanouil-html

execute:
  freeze: auto
  echo: false

filters:
  - at: post-ast
    path: include-code-files
  - at: pre-quarto
    path: highlight-text
  - at: post-quarto
    path: div-reuse
  - at: post-quarto
    path: remember

extensions:
  mcanouil:
    grid-background: true
